### ISSUE TITLE
Tecnologias Utilizadas

### ISSUE THREAD

**Issue by fabianosf** [Comeloo/Arquitetutra#2]
#Tecnologias Utilizadas : 
Linguagem Java
Banco de Dados : MySQL - definido
Framework JPA ou JDBC ??
Frontend - Angular, JSF, JSP ??

**Comment by RobsonSales** [comment]
Minha opinião seria JPA
Front o ideal seria Angular ou JSF.

**Comment by vicenthy** [comment]
Issue duplicada 
https://github.com/Comeloo/Arquitetutra/issues/1
